### ISSUE TITLE
Upgrade Kotlin to v1.6 across the board

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relayverse#39]
I've been putting this off due to the nightmares caused by the Kotlin 1.5 upgrade, but I'd like to think it'd be different this time.

The most important lesson I learnt last time is to do the upgrade in the following phases, to make debugging manageable:

1. Upgrade all the build- and run-time dependencies in the Awala libraries* (core, PoWeb, etc), but don't upgrade Kotlin yet.
1. Upgrade all the build/runtime/testing/etc dependencies in the apps* (Gateway, Courier and Ping), but don't upgrade Kotlin yet.
1. Test the apps and fix any upgrade issues.
1. Upgrade Kotlin across all libraries and merge into the main branch.
2. Update the apps to use Kotlin 1.6 along with the latest versions of the Awala libraries.

\* I'd rather defer the upgrade to ktor v2 if we can, because that's a mini project in its own right.

Thoughts, @sdsantos?

**Comment by sdsantos** [comment]
@gnarea sounds like a good plan. I'm not sure how far being we are on the other dependencies to assess how risky it is to skip steps 1 and 2. Nevertheless, this needs one of those huge todo lists with all the steps for all the repos.

**Comment by gnarea** [comment]
Great! Based on past experience, my hunch is that anything that isn't ktor/kotlin will be easy to upgrade, but I could be proven wrong!

**Comment by sdsantos** [comment]
So, here's a big to-do list:

1. Upgrade all the build- and run-time dependencies in the Awala libraries* (core, PoWeb, etc), but don't upgrade Kotlin yet.

- [x] awala-jvm (no update needed)
- [x] awala-testing-jvm (https://github.com/relaycorp/awala-testing-jvm/pull/86)
- [x] awala-poweb-jvm (https://github.com/relaycorp/awala-poweb-jvm/pull/222)
- [x] awala-cogrpc-jvm (https://github.com/relaycorp/awala-cogrpc-jvm/pull/244)
- [x] awala-cogrpc-okhttp-jvm (https://github.com/relaycorp/awala-cogrpc-okhttp-jvm/pull/100)
- [x] awala-keystore-file-jvm (https://github.com/relaycorp/awala-keystore-file-jvm/pull/50)
- [x] awala-endpoint-android (https://github.com/relaycorp/awala-endpoint-android/pull/236)

2. Upgrade all the build/runtime/testing/etc dependencies in the apps* (Gateway, Courier and Ping), but don't upgrade Kotlin yet.

- [x] awala-courier-android (https://github.com/relaycorp/relaynet-courier-android/pull/521)
- [x] awala-gateway-android (https://github.com/relaycorp/relaynet-gateway-android/pull/623)
- [x] awala-ping-android (https://github.com/relaycorp/awala-ping-android/pull/249)

3. Test the apps and fix any upgrade issues.

- [x] awala-courier-android
- [x] awala-gateway-android
- [x] awala-ping-android

4. Upgrade Kotlin across all libraries and merge into the main branch.

- [ ] awala-jvm
- [ ] awala-testing-jvm
- [ ] awala-poweb-jvm
- [ ] awala-cogrpc-jvm
- [ ] awala-cogrpc-okhttp-jvm
- [ ] awala-keystore-file-jvm
- [ ] awala-endpoint-android

5. Update the apps to use Kotlin 1.6 along with the latest versions of the Awala libraries. (defer the upgrade to ktor v2 if possible)

- [ ] awala-courier-android
- [ ] awala-gateway-android
- [ ] awala-ping-android

6. Extra issues (optional)

- [ ] https://github.com/relaycorp/awala-cogrpc-jvm/issues/250

**Comment by gnarea** [comment]
LGTM 👌🏾 

FYI, there's also the DoH library, but an external contributor is working on it (https://github.com/relaycorp/doh-jvm/pull/128). It does mean, however, that we can't upgrade the DoH lib in the apps for the time being.

**Comment by Filmaluco** [comment]
Related to point 2. awala-ping-android task the PR can be found here:
https://github.com/relaycorp/awala-ping-android/pull/249

**Comment by Filmaluco** [comment]
Related to point 2. awala-gateway-android task the PR can be found here:
https://github.com/relaycorp/relaynet-gateway-android/pull/623

**Comment by Filmaluco** [comment]
Related to point 2. relaynet-courier-android task the PR can be found here:
https://github.com/relaycorp/relaynet-courier-android/pull/521

**Comment by Filmaluco** [comment]
Related to point 3, I tested both the Gateway and the Ping app... and issues should be fixed on the branches aboves

**Comment by gnarea** [comment]
> Related to point 3, I tested both the Gateway and the Ping app

Do you mean both apps had the latest code from those branches?

**Comment by Filmaluco** [comment]
@gnarea yes :) 
update: (08/06/2022) I have now also tested Courier

**Comment by Filmaluco** [comment]
Related to task 4: ✅

Except [awala-poweb-jvm](https://github.com/relaycorp/awala-poweb-jvm) is missing on PRs approvals for:
* https://github.com/relaycorp/awala-poweb-jvm/pull/228
* https://github.com/relaycorp/awala-poweb-jvm/pull/229

**Comment by Filmaluco** [comment]
@gnarea awala-gateway-android still is using 1.5.21, (point 5.) is the last one missing, I will take care of it but worth mentioning.

**Comment by gnarea** [comment]
Good catch @Filmaluco! That TODO list is out-of-date but I thought all the apps were updated. I'll reopen this.

**Comment by Filmaluco** [comment]
@gnarea I believe this can now be closed :D
