### ISSUE TITLE
Port changes to communicate across Internet gateways in Android apps

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relayverse#40]
We have to port [some backwardly-incompatible changes](https://github.com/relaycorp/awala-jvm/pull/254) from the JVM lib in order to fix a [wider issue in the protocol](https://github.com/relaycorp/relayverse/issues/19). I already ported them to the Courier app but we still have to port them to the Ping and Gateway apps.

The high-level changes are:

- All RAMF messages (e.g., parcels, cargoes) will now contain the private address of the recipient (still derived from its identity key) and, optionally, the public address of the recipient (e.g., "braavos.relaycorp.cloud"). The public address is only required when the message is going to the Internet. (Previously, either the private or public address was specified)
- `Parcel.validate()`/`Cargo.validate()` used to take two parameters (`recipientType: RecipientType, trustedCertificates?: List<Certificate> = null`), but now it only takes the optional parameter `trustedCertificates`. This means that we *might* have one redundant test after this change, which should be removed.
- As a consequence of the changes above, the following terms were renamed (some some classes and fields have new names):
  -  "public address" -> "Internet address"
  -  "public gateway" -> "Internet gateway"
  -  "private address" -> "id"

So this is basically what we have to do:

- [x] Upgrade the `awala` and `awala-testing` to the latest versions in the [endpoint lib](https://github.com/relaycorp/awala-endpoint-android). Whilst we're there, we should also rename all variations of the terms "public address", "public gateway" and "private address".
- [x] Upgrade the Awala endpoint lib in the Awala Ping app. Whilst we're there, we should also rename all variations of the terms "public address", "public gateway" and "private address".
- [x] Upgrade the `awala` and `awala-testing` to the latest versions in the Awala Gateway. Whilst we're there, we should also rename all variations of the terms "public address", "public gateway" and "private address".

**Comment by Filmaluco** [comment]
PR for the first step:
https://github.com/relaycorp/awala-endpoint-android/pull/263

2nd step pending 1st
