### ISSUE TITLE
Upgrade Android Apps to compile and target SDK 33

### ISSUE THREAD

**Issue by Filmaluco** [relaycorp/relayverse#41]
We should go through all the Android Apps and update the compile and target SDK to api 33.
As we already saw with [Courier #596](https://github.com/relaycorp/relaynet-courier-android/issues/569) this change might require a few changes in the code base to support the newest version of Android.

* Endpoint
* Gateway
* Ping
* Courier

**Comment by gnarea** [comment]
Is this complete now @Filmaluco ?

**Comment by Filmaluco** [comment]
no, https://github.com/relaycorp/relaynet-gateway-android/pull/675 still is missing the merge. and the full test suite after
