### ISSUE TITLE
Upgrade Kotlin to v1.8 across the board

### ISSUE THREAD

**Issue by sdsantos** [relaycorp/relayverse#43]
Time to upgrade from Kotlin 1.6 to 1.8 across all libraries and apps. Here's the plan:

1. Upgrade Kotlin across all libraries and merge into the main branch.

- [x] awala-jvm
- [x] awala-testing-jvm
- [x] awala-poweb-jvm
- [x] awala-cogrpc-jvm
- [x] awala-cogrpc-okhttp-jvm
- [x] awala-keystore-file-jvm
- [x] awala-endpoint-android

2. Update the apps to use Kotlin 1.8 along with the latest versions of the Awala libraries.

- [x] awala-courier-android
- [x] awala-gateway-android
- [x] awala-ping-android

**Comment by gnarea** [comment]
Thanks! All looks good! 💪🏾

**Comment by Filmaluco** [comment]
[PR opened](https://github.com/relaycorp/awala-poweb-jvm/pull/252) for awala-poweb-jvm. 
Take a look, and mark it as done once approved @sdsantos

**Comment by Filmaluco** [comment]
[PR opened](https://github.com/relaycorp/awala-endpoint-android/pull/292) for awala-endpoint-android
Take a look, and mark it as done once approved @sdsantos
