### ISSUE TITLE
Drop Android 5 support across the board

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relayverse#45]
- [ ] Endpoint library.
- [ ] Courier.
- [ ] Gateway.
- [ ] Ping.

**Comment by sdsantos** [comment]
This is done right @gnarea?

**Comment by gnarea** [comment]
Almost @sdsantos. I did a super quick check and found a couple of "leftovers" -- there may be more:

- We're still testing Android 5 on CI: https://github.com/relaycorp/awala-ping-android/blob/3c815d97faeae655c248da4316c9abfe08c3cce1/app/firebase-test-lab.yml#L7-L11
- Outdated reference to Android 5 on README: https://github.com/relaycorp/relaynet-gateway-android#no-encryption-at-rest-on-android-5

**Comment by sdsantos** [comment]
> Almost @sdsantos. I did a super quick check and found a couple of "leftovers" -- there may be more:
> 
> * We're still testing Android 5 on CI: https://github.com/relaycorp/awala-ping-android/blob/3c815d97faeae655c248da4316c9abfe08c3cce1/app/firebase-test-lab.yml#L7-L11
> * Outdated reference to Android 5 on README: https://github.com/relaycorp/relaynet-gateway-android#no-encryption-at-rest-on-android-5

PRs created for those. Couldn't find any more as well.

**Comment by gnarea** [comment]
Awesome, thanks!
