### ISSUE TITLE
Upgrade Gradle and AGP to v8

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relayverse#48]
- [x] Gateway.
- [x] Courier.
- [x] Endpoint library.
- [x] Ping.

**Comment by sdsantos** [comment]
All PRs created

**Comment by gnarea** [comment]
Thanks! They're all approved and set to auto-merge so we can close this once they're all merged.

**Comment by sdsantos** [comment]
@gnarea we can close this

**Comment by gnarea** [comment]
Thanks @sdsantos !
